widget/plus.htm
input attributes for widget: jsonLd object with ItemList in it, will bw taken from scope like 
var webrunes = window.webrunes || {};
webrunes.jsonlds['ItemList'].
1. creates relationship parent-child according to parent.url and child.author properties (should be the same for connection) - plusWidget.groupByAthour
2. creates markup for accordion (tabs) based on provided relashionship -plusWidget.createdCallback.
=> plus widget implementation

widget/plus.htm
=> change amazon link

widget/plus.htm
=> enable Plus widget draw

public/scripts/hub.js, widget/plus.htm
=> fix hub.js to store object directly

widget/plus.htm
=> fix for JSON.parse('empty object')

widget/plus.htm, widget/storageHub.htm
=> update Plus widget to use common localStorage url

public/scripts/hub.js, widget/plus.htm, widget/storageHub.htm
=> added 'wrio' domain access to storage

widget/storageHub.htm
=> added cross-domain permission for 'alexeyanshakov'

js/plus.js
https://github.com/webRunes/Plus-WRIO-App/issues/58
=> index.htm. Reward ??? USD #58 (plus.js update for remove index from url)

widget/plus.htm
Update plus.htm for "+" tab. 
https://github.com/webRunes/Plus-WRIO-App/issues/55
=> Plus tab "+". Reward 50 USD #55

js/plus.js
https://github.com/webRunes/Default-WRIO-Theme/issues/64
=> Article with lists #64 (update plus.js to remove tab)

js/plus.js
https://github.com/webRunes/Plus-WRIO-App/issues/68
=> #anchor bug #68 (update plus.js for remove two tab)

js/plus.js
https://github.com/webRunes/Plus-WRIO-App/issues/68
=> #anchor bug #68 (update plus.js again for plus tab)

js/client.js, js/plus.js
https://github.com/webRunes/WRIO-InternetOS/issues/151
=> Browserify: update client and plus

js/client.js
https://github.com/webRunes/Titter-WRIO-App/issues/84
http://i.imgur.com/zHED0dQ.png
IE not support "Promise" (http://caniuse.com/#feat=promises)
I fix it with https://github.com/petkaantonov/bluebird
=> Add Promise support by bluebird

js/P.js, js/Plus.js, js/stores/jsonld.js, package.json
https://github.com/webRunes/Plus-WRIO-App/issues/85
done:
*в IE при переключении между 
http://webrunes.com/
и
http://wrioos.com/
меняются местами child в родительском табе "webRunes". Child должны отображаться исходя из своего физ. расположения в plus json-ld.
*child после удаления снова виден после перехода на др. страницу или F5
не отлажено , готова только структура:
*Expand/collapse должен работать при посещении страницы, не динамически. Т.е. при нажатии на родительский таб нужно переходить на его страницу, а не expand/collapse как это работало в предыдущей версии на сайте. В прототипе так сделано лишь для примера отображения состояний.
=> Position of element is fixed. Parent tab should be clickable element

js/Element.js, js/Plus.js, js/stores/jsonld.js, package.json
https://github.com/webRunes/Plus-WRIO-App/issues/85
=> Set current element as active

.travis.yml, js/Element.js, js/Plus.js, js/stores/jsonld.js, package.json
https://github.com/webRunes/Plus-WRIO-App/issues/85
=> Tab elements

js/Plus.js
https://github.com/webRunes/Plus-WRIO-App/issues/85
Show tab's sub tabs only if inside there is active tab
=> Plus issues

js/Element.js, js/Plus.js
https://github.com/webRunes/Default-WRIO-Theme/issues/97
=> Plus ticket issue #97: edit styles for Plus widget

js/Plus.js
webRunes/Default-WRIO-Theme/#97
=> Plus ticket issue #97: fixed a bug after testing eslint

default/index.htm
https://github.com/webRunes/Plus-WRIO-App/issues/132
=>  Default list #132: start.js link has been added

js/P.js, js/Plus.js
https://github.com/webRunes/Default-WRIO-Theme/issues/97
=> Plus ticket issue #97: Expanded click-zone and add block color

js/P.js, js/Plus.js
https://github.com/webRunes/Default-WRIO-Theme/issues/97
=> Plus ticket issue #97: Plus update style for nested tabs

gulpfile.js, js/.eslintrc, js/List.js, js/P.js, package.json
https://github.com/webRunes/Plus-WRIO-App/issues/132
https://github.com/webRunes/Default-WRIO-Theme/issues/97
=> Default list #132 #97: User_id for + and child checker

js/P.js, package.json
+ tabs dont working without 'http:'
=> + tabs dont working without 'http:'

js/P.js, package.json
Reverts webRunes/Plus-WRIO-App#141
=> Revert "+ tabs dont working without 'http:'"

js/P.js
=> HttpChecker add

js/P.js
=> Eslint error setstate

js/List.js, js/Plus.js, js/actions/menu.js, js/stores/menu.js
=> Mobile UI #72: part 

js/List.js, js/Plus.js, js/stores/menu.js
=> Mobile UI #97: 'Check eslint error'

js/Plus.js
=> Mobile UI #72: reflux fix

js/List.js, js/Plus.js
=> Mobile UI #72: FIX

js/List.js, js/P.js, js/Plus.js, js/stores/menu.js
=> Mobile UI #72: fixed bugs

js/List.js, js/Plus.js, js/actions/menu.js, js/stores/menu.js
=> Mobile UI #72: resize listener add

js/List.js
=> Mobile UI #72: fix scroll

js/List.js, js/P.js
https://github.com/webRunes/Default-WRIO-Theme/issues/139
=> UI issues #139

js/P.js, js/Plus.js
=> UI issue #175: Fix active PLUS

js/Item.js, js/List.js, js/Plus.js
https://github.com/webRunes/Plus-WRIO-App/issues/178
https://github.com/webRunes/Plus-WRIO-App/issues/179
=> Save scroll menu position #179 #178

js/List.js, js/Plus.js
https://github.com/webRunes/WRIO-InternetOS/issues/403
=> Help message: fix

js/Item.js, js/SubList.js
https://github.com/webRunes/Plus-WRIO-App/issues/188
=> URL visibility #188: URL Visibility

js/P.js, js/stores/jsonld.js, js/utils/servicelocator.js
minor imports cleanup
https://github.com/webRunes/WRIO-InternetOS/issues/17
=> Add SSL #17 Fix storageHub url to https

js/Item.js, js/List.js, js/Plus.js, js/SubList.js, js/stores/jsonld.js
https://github.com/webRunes/Plus-WRIO-App/issues/189
=> Remove first visit tabs #189

js/Item.js, js/stores/CrossStorageFactory.js, js/stores/jsonld.js, js/stores/normURL.js, test/JsonLDStoreTest.js, test/index.html, test/index.js, test/itemtest.js, test/normURLtest.js
can be merged after all checks pass
=> Save link protocol in the crossStorage #209, plus cleanup and tests

gulpfile.js
https://github.com/webRunes/WRIO-InternetOS/issues/647
=> htm -> html #647
